name: "Workflow TP5"

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build e Teste Backend
        run: |
          cd TP4-PB-Backend
          mvn clean package -DskipTests
          mvn test -DtestFailureIgnore=true

      - name: Upload do JAR (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: api-produto-jar
          path: TP4-PB-Backend/target/*.jar

      - name: Validar Link de Produção
        run: |
          echo "Verificando se o sistema está online no Railway..."
          curl -I https://tp5-pb-production.up.railway.app/produtos || echo "Sistema Offline"

      - name: Resumo
        if: always()
        run: |
          echo "## Relatório TP5 Concluído" >> $GITHUB_STEP_SUMMARY
          echo "1. **Build:** Maven executado." >> $GITHUB_STEP_SUMMARY
          echo "2. **Artefatos:** Arquivo JAR e cobertura disponíveis." >> $GITHUB_STEP_SUMMARY
          echo "3. **Deploy:** Verificado no Railway." >> $GITHUB_STEP_SUMMARY
          echo "4. **Link:** https://frontend-production-ef1c.up.railway.app" >> $GITHUB_STEP_SUMMARY

      - name: Upload Relatorio Jacoco
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura
          path: TP4-PB-Backend/target/site/jacoco/